name: Update Jira Task and Notify Slack

on:
  push:
    branches:
      - main  

jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: get_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Extract Jira Issue Key
        id: extract_key
        run: |
          echo "JIRA_KEY=$(echo '${{ steps.get_commit.outputs.message }}' | grep -o -E 'SCRUM-[0-9]+' | head -n 1)" >> $GITHUB_ENV

      - name: Get XSRF Token
        id: get_xsrf_token
        run: |
          echo "Requesting XSRF token..."
          XSRF_TOKEN=$(curl -k -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" \
          -X GET \
          -H "Content-Type: application/json" \
          "${{ secrets.JIRA_URL }}/rest/api/2/myself" \
          | grep -oP 'atlassian.xsrf.token=\K[^;]+')

          if [ -z "$XSRF_TOKEN" ]; then
              echo "Failed to retrieve XSRF token"
              exit 1
          fi

          echo "XSRF_TOKEN=$XSRF_TOKEN" >> $GITHUB_ENV

      - name: Update Jira Task
        if: env.JIRA_KEY != ''
        run: |
          curl -k -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "X-Atlassian-Token: ${{ env.XSRF_TOKEN }}" \
          --data '{"transition":{"id":"31"}}' \
          "${{ secrets.JIRA_URL }}/rest/api/2/issue/${{ env.JIRA_KEY }}/transitions"

      - name: Notify Slack
        if: env.JIRA_KEY != ''
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "La tâche '${{ env.JIRA_KEY }}' a été marquée comme faite!"}' ${{ secrets.SLACK_WEBHOOK_URL }}